version: "3.9"

services:
  redis:
    image: redis
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
  app:
    build:
      context: .
      dockerfile: dockerfile.Development
    container_name: beatmapbot
    environment:
     -  REDIS_URL=redis://redis:6379
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - redis
